### ISSUE TITLE
 upload: "Загрузить",

### ISSUE THREAD

**Issue by GiantappMan** [giant-app/livewallpaper_i18n#2]
hi @vanja-san,
Pls. check whether this one is wrong?

**Comment by GiantappMan** [comment]
![image](https://user-images.githubusercontent.com/80653/109264043-4a509580-783f-11eb-9653-99288d886a97.png)
![image](https://user-images.githubusercontent.com/80653/109264057-50467680-783f-11eb-9bfb-69b4e35dc035.png)

It's kind of weird...

**Comment by vanja-san** [comment]
No, that's right. That's how it's spelled in both cases. 😄

**Comment by GiantappMan** [comment]
Ok, thanks again, your PR has updated https://livewallpaper.giantapp.cn/ru/wallpapers

**Comment by vanja-san** [comment]
There are untranslated words on registration page.


![изображение](https://user-images.githubusercontent.com/7201687/109457266-1bc7fa00-7a8d-11eb-8f57-a8d0ed069593.png)

**Comment by GiantappMan** [comment]
Some translations haven't been finished yet, I'm working on this

**Comment by vanja-san** [comment]
No problems! If it is not difficult, let know when me need to start translating. 😊

**Comment by GiantappMan** [comment]
It would be appreciated if you could check the grammar for the Russian translation.
I should be able to finish the translation this week.

**Comment by GiantappMan** [comment]
fixed https://livewallpaper.giantapp.cn/ru/register
