### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by SirmauricioCL** [giant-app/livewallpaper_i18n#4]
Hi, I'm trying to upload the Spanish translation and it throws me the following error in Visual Studio:

Failed to push branch to remote repository: Git failed with a fatal error.
Git failed with a fatal error.
unable to access 'https://github.com/giant-app/livewallpaper_i18n.git/': The requested URL returned error: 403

**Comment by GiantappMan** [comment]
Hi @SirmauricioCL,
You should fork this repository and commit in your replica repository, then pull requests to this repository.
